
name: ci
on:
  push:
  pull_request:
jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build -p mmx-cli -F mmx-core/gst --release
      - run: bash scripts/smoke_samples.sh
      - run: BIN=target/release/mmx bash scripts/smoke_tier0.sh
