name: CI

on:
  push:
    branches:
      - master
      - main
      - 'roadmap-**'
      - 'feature/**'
  pull_request:
    branches:
      - master
      - main

jobs:
  build-and-smoke-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install GStreamer (base+good+bad)
        run: |
          brew update
          brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad || true
      - name: Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release -p mmx-cli --bin mmx-remux
      - name: Smoke tests
        run: |
          chmod +x scripts/*.sh || true
          if [[ -x scripts/smoke_gen_fixture_mp4.sh ]]; then ./scripts/smoke_gen_fixture_mp4.sh; fi
          if [[ -x scripts/smoke_remux_mp4_to_mkv.sh ]]; then ./scripts/smoke_remux_mp4_to_mkv.sh; fi

  guard-pr-size:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if PR too large (>1500 lines changed)
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.sha }}"
          changed=$(git diff --shortstat "$base" "$head" | sed -E 's/[^0-9]+/ /g' | awk '{print ($1+$2)}')
          echo "Changed lines: ${changed:-0}"
          test "${changed:-0}" -le 1500 || { echo "PR too large. Please split."; exit 1; }
