name: Join program auto-reply
on:
  issues:
    types: [opened]
jobs:
  reply:
    if: contains(github.event.issue.labels.*.name, 'onboarding')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const body = `
Thanks for applying! :tada:

**Next steps**
1. Create a Stripe account (if you haven't): https://dashboard.stripe.com/register
2. Read training quickstart: \`docs/TRAINING.md\`
3. Pick or ask for an onboarding ticket; we’ll assign a small, paid starter task.

**How we work**
- Small PRs (< 500 lines), green CI required.
- Put risky code behind the \`experimental\` Cargo feature.
- Never share secrets or private keys on GitHub.

We’ll follow up by email.
`;
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.payload.issue.number,
              body
            });
