name: release
on:
  push:
    tags:
      - "v*"
jobs:
  macos-universal:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: bash scripts/mmx_release.sh universal || true
      - run: bash scripts/mmx_release_extras.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.sha256
