name: Release
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build CLI
        run: cargo build -p mmx-cli -F mmx-core/gst --release
      - name: Pack SDK
        run: |
          mkdir -p dist
          tar -czf dist/mmx-sdk.tar.gz mmx-core mmx-cli
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mmx-sdk.tar.gz
